[colors.bright]
black    =  "0x657b83"
blue     =  "0x268bd2"
cyan     =  "0x2aa198"
green    =  "0x859900"
magenta  =  "0x6c71c4"
red      =  "0xdc322f"
white    =  "0xfdf6e3"
yellow   =  "0xb58900"
[colors.normal]
black    =  "0x002b36"
blue     =  "0x268bd2"
cyan     =  "0x2aa198"
green    =  "0x859900"
magenta  =  "0x6c71c4"
red      =  "0xdc322f"
white    =  "0x93a1a1"
yellow   =  "0xb58900"
[colors.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
family = "Fantasque Sans Mono"

[font.italic]
family = "Fantasque Sans Mono"

[font.normal]
family = "Fantasque Sans Mono"

[font.offset]
x = 0
y = 0

[window.padding]
x = 2
y = 2
