[package]
name = "limebar-rs"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
chrono="*"
i3ipc="*"
mpd="*"
systemstat="*"
